title: Rahma Amalia # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  An undergraduate degree holder in Informatics Engineering from Universitas Negeri Surabaya. Highly motivated to learn new things, detail-oriented, and aspiring to work as a Data Analyst or Data Scientist. Proficient in developing data products such as dashboards and experienced in data analysis using Python.
  <br></br>
  <a href="https://www.linkedin.com/in/rahmaamalia26/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
